const fs = require('fs');
let code = fs.readFileSync('src/data/componentsLibrary.ts', 'utf8');

const newComponents = `
  // ==================== FLIP FLOPS ====================
  {
    id: 'ic-7474-d',
    name: '7474 Dual D Flip-Flop (DIP-14)',
    category: 'Logic & IC',
    tagline: '2 D Flip-Flops • Edge-Triggered',
    description: 'Dual D-Type Positive-Edge-Triggered Flip-Flop with Preset and Clear.',
    workingPrinciple: 'Stores 1 bit of data on the positive edge of the clock.',
    operatingVoltage: '4.75V - 5.25V DC',
    operatingCurrent: '15 mA Max',
    icSeries: '7474',
    gateName: 'D Flip-Flop',
    gateFunction: 'Data Storage',
    gateCountText: '2 D Flip-Flops',
    logicExpressionDisplay: 'Q = D (on CLK ↑)',
    logicSymbolType: 'CUSTOM',
    booleanEquation: 'Q_next = D',
    truthTableData: [],
    datasheetSummary: { manufacturer: 'Generic', icChip: '7474', logicLevels: 'TTL', operatingTemp: '0-70C' },
    pins: [
      { id: 'pin-1', name: '1CLR\\'', type: 'IN', relativePos: [-0.72, -0.22, 0.62], description: 'Clear 1 (Active Low)', gateNumber: 1, gateRole: 'CLR' },
      { id: 'pin-2', name: '1D', type: 'IN', relativePos: [-0.48, -0.22, 0.62], description: 'Data 1', gateNumber: 1, gateRole: 'D' },
      { id: 'pin-3', name: '1CLK', type: 'IN', relativePos: [-0.24, -0.22, 0.62], description: 'Clock 1', gateNumber: 1, gateRole: 'CLK' },
      { id: 'pin-4', name: '1PR\\'', type: 'IN', relativePos: [0.0, -0.22, 0.62], description: 'Preset 1 (Active Low)', gateNumber: 1, gateRole: 'PR' },
      { id: 'pin-5', name: '1Q', type: 'OUT', relativePos: [0.24, -0.22, 0.62], description: 'Output Q1', gateNumber: 1, gateRole: 'Q' },
      { id: 'pin-6', name: '1Q\\'', type: 'OUT', relativePos: [0.48, -0.22, 0.62], description: 'Output Q1\\'', gateNumber: 1, gateRole: 'Q_INV' },
      { id: 'pin-7', name: 'GND', type: 'GND', relativePos: [0.72, -0.22, 0.62], description: 'Ground', gateRole: 'GND' },
      { id: 'pin-8', name: '2Q\\'', type: 'OUT', relativePos: [0.72, -0.22, -0.62], description: 'Output Q2\\'', gateNumber: 2, gateRole: 'Q_INV' },
      { id: 'pin-9', name: '2Q', type: 'OUT', relativePos: [0.48, -0.22, -0.62], description: 'Output Q2', gateNumber: 2, gateRole: 'Q' },
      { id: 'pin-10', name: '2PR\\'', type: 'IN', relativePos: [0.24, -0.22, -0.62], description: 'Preset 2 (Active Low)', gateNumber: 2, gateRole: 'PR' },
      { id: 'pin-11', name: '2CLK', type: 'IN', relativePos: [0.0, -0.22, -0.62], description: 'Clock 2', gateNumber: 2, gateRole: 'CLK' },
      { id: 'pin-12', name: '2D', type: 'IN', relativePos: [-0.24, -0.22, -0.62], description: 'Data 2', gateNumber: 2, gateRole: 'D' },
      { id: 'pin-13', name: '2CLR\\'', type: 'IN', relativePos: [-0.48, -0.22, -0.62], description: 'Clear 2 (Active Low)', gateNumber: 2, gateRole: 'CLR' },
      { id: 'pin-14', name: 'VCC', type: 'VCC', relativePos: [-0.72, -0.22, -0.62], description: '+5V Power', gateRole: 'VCC' }
    ]
  },
  {
    id: 'ic-jk-ff',
    name: 'Dual JK Flip-Flop (DIP-14)',
    category: 'Logic & IC',
    tagline: '2 JK Flip-Flops • Edge-Triggered',
    description: 'Dual JK Flip-Flop (Idealized DIP-14 with standard power pins).',
    workingPrinciple: 'Toggles, sets, or resets based on J and K inputs on clock edge.',
    operatingVoltage: '4.75V - 5.25V DC',
    operatingCurrent: '15 mA Max',
    icSeries: 'JK-FF',
    gateName: 'JK Flip-Flop',
    gateFunction: 'Toggle / Storage',
    gateCountText: '2 JK Flip-Flops',
    logicExpressionDisplay: 'Q = JQ\\' + K\\'Q',
    logicSymbolType: 'CUSTOM',
    booleanEquation: 'Q_next = JQ\\' + K\\'Q',
    truthTableData: [],
    datasheetSummary: { manufacturer: 'Generic', icChip: 'JK-FF', logicLevels: 'TTL', operatingTemp: '0-70C' },
    pins: [
      { id: 'pin-1', name: '1J', type: 'IN', relativePos: [-0.72, -0.22, 0.62], gateNumber: 1, gateRole: 'J' },
      { id: 'pin-2', name: '1K', type: 'IN', relativePos: [-0.48, -0.22, 0.62], gateNumber: 1, gateRole: 'K' },
      { id: 'pin-3', name: '1CLK', type: 'IN', relativePos: [-0.24, -0.22, 0.62], gateNumber: 1, gateRole: 'CLK' },
      { id: 'pin-4', name: '1Q', type: 'OUT', relativePos: [0.0, -0.22, 0.62], gateNumber: 1, gateRole: 'Q' },
      { id: 'pin-5', name: '1Q\\'', type: 'OUT', relativePos: [0.24, -0.22, 0.62], gateNumber: 1, gateRole: 'Q_INV' },
      { id: 'pin-6', name: '1CLR\\'', type: 'IN', relativePos: [0.48, -0.22, 0.62], gateNumber: 1, gateRole: 'CLR' },
      { id: 'pin-7', name: 'GND', type: 'GND', relativePos: [0.72, -0.22, 0.62], gateRole: 'GND' },
      { id: 'pin-8', name: '2CLR\\'', type: 'IN', relativePos: [0.72, -0.22, -0.62], gateNumber: 2, gateRole: 'CLR' },
      { id: 'pin-9', name: '2Q\\'', type: 'OUT', relativePos: [0.48, -0.22, -0.62], gateNumber: 2, gateRole: 'Q_INV' },
      { id: 'pin-10', name: '2Q', type: 'OUT', relativePos: [0.24, -0.22, -0.62], gateNumber: 2, gateRole: 'Q' },
      { id: 'pin-11', name: '2CLK', type: 'IN', relativePos: [0.0, -0.22, -0.62], gateNumber: 2, gateRole: 'CLK' },
      { id: 'pin-12', name: '2K', type: 'IN', relativePos: [-0.24, -0.22, -0.62], gateNumber: 2, gateRole: 'K' },
      { id: 'pin-13', name: '2J', type: 'IN', relativePos: [-0.48, -0.22, -0.62], gateNumber: 2, gateRole: 'J' },
      { id: 'pin-14', name: 'VCC', type: 'VCC', relativePos: [-0.72, -0.22, -0.62], gateRole: 'VCC' }
    ]
  },
  {
    id: 'ic-sr-ff',
    name: 'Dual SR Latch/Flip-Flop (DIP-14)',
    category: 'Logic & IC',
    tagline: '2 SR Flip-Flops',
    description: 'Dual Set-Reset Flip-Flop (Idealized DIP-14 with standard power pins).',
    workingPrinciple: 'Sets or resets output based on S and R inputs on clock edge.',
    operatingVoltage: '4.75V - 5.25V DC',
    operatingCurrent: '15 mA Max',
    icSeries: 'SR-FF',
    gateName: 'SR Flip-Flop',
    gateFunction: 'Storage Latch',
    gateCountText: '2 SR Flip-Flops',
    logicExpressionDisplay: 'Q = S + R\\'Q',
    logicSymbolType: 'CUSTOM',
    booleanEquation: 'Q_next = S + R\\'Q',
    truthTableData: [],
    datasheetSummary: { manufacturer: 'Generic', icChip: 'SR-FF', logicLevels: 'TTL', operatingTemp: '0-70C' },
    pins: [
      { id: 'pin-1', name: '1S', type: 'IN', relativePos: [-0.72, -0.22, 0.62], gateNumber: 1, gateRole: 'S' },
      { id: 'pin-2', name: '1R', type: 'IN', relativePos: [-0.48, -0.22, 0.62], gateNumber: 1, gateRole: 'R' },
      { id: 'pin-3', name: '1CLK', type: 'IN', relativePos: [-0.24, -0.22, 0.62], gateNumber: 1, gateRole: 'CLK' },
      { id: 'pin-4', name: '1Q', type: 'OUT', relativePos: [0.0, -0.22, 0.62], gateNumber: 1, gateRole: 'Q' },
      { id: 'pin-5', name: '1Q\\'', type: 'OUT', relativePos: [0.24, -0.22, 0.62], gateNumber: 1, gateRole: 'Q_INV' },
      { id: 'pin-6', name: 'NC', type: 'NC', relativePos: [0.48, -0.22, 0.62], gateRole: 'NC' },
      { id: 'pin-7', name: 'GND', type: 'GND', relativePos: [0.72, -0.22, 0.62], gateRole: 'GND' },
      { id: 'pin-8', name: 'NC', type: 'NC', relativePos: [0.72, -0.22, -0.62], gateRole: 'NC' },
      { id: 'pin-9', name: '2Q\\'', type: 'OUT', relativePos: [0.48, -0.22, -0.62], gateNumber: 2, gateRole: 'Q_INV' },
      { id: 'pin-10', name: '2Q', type: 'OUT', relativePos: [0.24, -0.22, -0.62], gateNumber: 2, gateRole: 'Q' },
      { id: 'pin-11', name: '2CLK', type: 'IN', relativePos: [0.0, -0.22, -0.62], gateNumber: 2, gateRole: 'CLK' },
      { id: 'pin-12', name: '2R', type: 'IN', relativePos: [-0.24, -0.22, -0.62], gateNumber: 2, gateRole: 'R' },
      { id: 'pin-13', name: '2S', type: 'IN', relativePos: [-0.48, -0.22, -0.62], gateNumber: 2, gateRole: 'S' },
      { id: 'pin-14', name: 'VCC', type: 'VCC', relativePos: [-0.72, -0.22, -0.62], gateRole: 'VCC' }
    ]
  },
  {
    id: 'ic-t-ff',
    name: 'Dual T Flip-Flop (DIP-14)',
    category: 'Logic & IC',
    tagline: '2 Toggle Flip-Flops',
    description: 'Dual T Flip-Flop (Idealized DIP-14 with standard power pins).',
    workingPrinciple: 'Toggles output when T is HIGH on clock edge.',
    operatingVoltage: '4.75V - 5.25V DC',
    operatingCurrent: '15 mA Max',
    icSeries: 'T-FF',
    gateName: 'T Flip-Flop',
    gateFunction: 'Toggle Latch',
    gateCountText: '2 T Flip-Flops',
    logicExpressionDisplay: 'Q = T ⊕ Q',
    logicSymbolType: 'CUSTOM',
    booleanEquation: 'Q_next = T ⊕ Q',
    truthTableData: [],
    datasheetSummary: { manufacturer: 'Generic', icChip: 'T-FF', logicLevels: 'TTL', operatingTemp: '0-70C' },
    pins: [
      { id: 'pin-1', name: '1T', type: 'IN', relativePos: [-0.72, -0.22, 0.62], gateNumber: 1, gateRole: 'T' },
      { id: 'pin-2', name: '1CLK', type: 'IN', relativePos: [-0.48, -0.22, 0.62], gateNumber: 1, gateRole: 'CLK' },
      { id: 'pin-3', name: '1CLR\\'', type: 'IN', relativePos: [-0.24, -0.22, 0.62], gateNumber: 1, gateRole: 'CLR' },
      { id: 'pin-4', name: '1Q', type: 'OUT', relativePos: [0.0, -0.22, 0.62], gateNumber: 1, gateRole: 'Q' },
      { id: 'pin-5', name: '1Q\\'', type: 'OUT', relativePos: [0.24, -0.22, 0.62], gateNumber: 1, gateRole: 'Q_INV' },
      { id: 'pin-6', name: 'NC', type: 'NC', relativePos: [0.48, -0.22, 0.62], gateRole: 'NC' },
      { id: 'pin-7', name: 'GND', type: 'GND', relativePos: [0.72, -0.22, 0.62], gateRole: 'GND' },
      { id: 'pin-8', name: 'NC', type: 'NC', relativePos: [0.72, -0.22, -0.62], gateRole: 'NC' },
      { id: 'pin-9', name: '2Q\\'', type: 'OUT', relativePos: [0.48, -0.22, -0.62], gateNumber: 2, gateRole: 'Q_INV' },
      { id: 'pin-10', name: '2Q', type: 'OUT', relativePos: [0.24, -0.22, -0.62], gateNumber: 2, gateRole: 'Q' },
      { id: 'pin-11', name: '2CLR\\'', type: 'IN', relativePos: [0.0, -0.22, -0.62], gateNumber: 2, gateRole: 'CLR' },
      { id: 'pin-12', name: '2CLK', type: 'IN', relativePos: [-0.24, -0.22, -0.62], gateNumber: 2, gateRole: 'CLK' },
      { id: 'pin-13', name: '2T', type: 'IN', relativePos: [-0.48, -0.22, -0.62], gateNumber: 2, gateRole: 'T' },
      { id: 'pin-14', name: 'VCC', type: 'VCC', relativePos: [-0.72, -0.22, -0.62], gateRole: 'VCC' }
    ]
  },
`;

code = code.replace(/\];\n\nexport const getComponentMeta =/, newComponents + '\n];\n\nexport const getComponentMeta =');
fs.writeFileSync('src/data/componentsLibrary.ts', code);
