const fs = require('fs');
let code = fs.readFileSync('src/data/componentsLibrary.ts', 'utf8');

const newICs = `
  // ==================== FLIP FLOPS ====================
  {
    id: 'ic-jk-ff',
    name: 'Dual JK Flip-Flop',
    category: 'Logic & IC',
    tagline: 'Synchronous edge-triggered JK flip-flop',
    description: 'A dual JK flip-flop that can set, reset, toggle, or hold state based on J and K inputs at the clock edge.',
    workingPrinciple: 'Combines cross-coupled gates with edge-trigger steering logic.',
    operatingVoltage: '4.75V to 5.25V',
    operatingCurrent: '15mA to 20mA',
    datasheetSummary: {
      manufacturer: 'Generic',
      interface: '14-pin DIP',
    },
    pins: [
      { id: 'pin-1', name: 'Pin 1 (1J)', type: 'IN', relativePos: [-0.72, -0.22, 0.62], description: 'Flip-Flop 1 J Input', gateNumber: 1, gateRole: 'J' },
      { id: 'pin-2', name: 'Pin 2 (1K)', type: 'IN', relativePos: [-0.48, -0.22, 0.62], description: 'Flip-Flop 1 K Input', gateNumber: 1, gateRole: 'K' },
      { id: 'pin-3', name: 'Pin 3 (1CLK)', type: 'IN', relativePos: [-0.24, -0.22, 0.62], description: 'Flip-Flop 1 Clock', gateNumber: 1, gateRole: 'CLK' },
      { id: 'pin-4', name: 'Pin 4 (1Q)', type: 'OUT', relativePos: [0.0, -0.22, 0.62], description: 'Flip-Flop 1 Q Output', gateNumber: 1, gateRole: 'Q' },
      { id: 'pin-5', name: 'Pin 5 (1Q\\')', type: 'OUT', relativePos: [0.24, -0.22, 0.62], description: 'Flip-Flop 1 Inverted Q Output', gateNumber: 1, gateRole: 'Q_INV' },
      { id: 'pin-6', name: 'Pin 6 (1CLR)', type: 'IN', relativePos: [0.48, -0.22, 0.62], description: 'Flip-Flop 1 Clear (Active Low)', gateNumber: 1, gateRole: 'CLR' },
      { id: 'pin-7', name: 'Pin 7 (GND)', type: 'GND', relativePos: [0.72, -0.22, 0.62], description: 'Ground', gateRole: 'GND' },
      { id: 'pin-8', name: 'Pin 8 (2Q\\')', type: 'OUT', relativePos: [0.72, -0.22, -0.62], description: 'Flip-Flop 2 Inverted Q Output', gateNumber: 2, gateRole: 'Q_INV' },
      { id: 'pin-9', name: 'Pin 9 (2Q)', type: 'OUT', relativePos: [0.48, -0.22, -0.62], description: 'Flip-Flop 2 Q Output', gateNumber: 2, gateRole: 'Q' },
      { id: 'pin-10', name: 'Pin 10 (2CLK)', type: 'IN', relativePos: [0.24, -0.22, -0.62], description: 'Flip-Flop 2 Clock', gateNumber: 2, gateRole: 'CLK' },
      { id: 'pin-11', name: 'Pin 11 (2K)', type: 'IN', relativePos: [0.0, -0.22, -0.62], description: 'Flip-Flop 2 K Input', gateNumber: 2, gateRole: 'K' },
      { id: 'pin-12', name: 'Pin 12 (2J)', type: 'IN', relativePos: [-0.24, -0.22, -0.62], description: 'Flip-Flop 2 J Input', gateNumber: 2, gateRole: 'J' },
      { id: 'pin-13', name: 'Pin 13 (2CLR)', type: 'IN', relativePos: [-0.48, -0.22, -0.62], description: 'Flip-Flop 2 Clear (Active Low)', gateNumber: 2, gateRole: 'CLR' },
      { id: 'pin-14', name: 'Pin 14 (VCC)', type: 'VCC', relativePos: [-0.72, -0.22, -0.62], description: 'VCC +5V', gateRole: 'VCC' },
    ],
    applications: ['Counters', 'Shift Registers'],
    dimensions: { x: 1.8, y: 0.3, z: 0.8 },
  },
  {
    id: 'ic-7474-d',
    name: 'Dual D Flip-Flop (7474)',
    category: 'Logic & IC',
    tagline: 'Dual Positive-Edge-Triggered D-Type Flip-Flops',
    description: 'A dual D-type flip-flop with clear and preset.',
    workingPrinciple: 'Captures D input at the positive clock edge.',
    operatingVoltage: '4.75V to 5.25V',
    operatingCurrent: '15mA',
    datasheetSummary: {
      manufacturer: 'Generic',
      interface: '14-pin DIP',
    },
    pins: [
      { id: 'pin-1', name: 'Pin 1 (1CLR)', type: 'IN', relativePos: [-0.72, -0.22, 0.62], description: 'Clear (Active Low)', gateNumber: 1, gateRole: 'CLR' },
      { id: 'pin-2', name: 'Pin 2 (1D)', type: 'IN', relativePos: [-0.48, -0.22, 0.62], description: 'Data Input', gateNumber: 1, gateRole: 'D' },
      { id: 'pin-3', name: 'Pin 3 (1CLK)', type: 'IN', relativePos: [-0.24, -0.22, 0.62], description: 'Clock Input', gateNumber: 1, gateRole: 'CLK' },
      { id: 'pin-4', name: 'Pin 4 (1PR)', type: 'IN', relativePos: [0.0, -0.22, 0.62], description: 'Preset (Active Low)', gateNumber: 1, gateRole: 'PR' },
      { id: 'pin-5', name: 'Pin 5 (1Q)', type: 'OUT', relativePos: [0.24, -0.22, 0.62], description: 'Q Output', gateNumber: 1, gateRole: 'Q' },
      { id: 'pin-6', name: 'Pin 6 (1Q\\')', type: 'OUT', relativePos: [0.48, -0.22, 0.62], description: 'Inverted Q Output', gateNumber: 1, gateRole: 'Q_INV' },
      { id: 'pin-7', name: 'Pin 7 (GND)', type: 'GND', relativePos: [0.72, -0.22, 0.62], description: 'Ground', gateRole: 'GND' },
      { id: 'pin-8', name: 'Pin 8 (2Q\\')', type: 'OUT', relativePos: [0.72, -0.22, -0.62], description: 'Inverted Q Output', gateNumber: 2, gateRole: 'Q_INV' },
      { id: 'pin-9', name: 'Pin 9 (2Q)', type: 'OUT', relativePos: [0.48, -0.22, -0.62], description: 'Q Output', gateNumber: 2, gateRole: 'Q' },
      { id: 'pin-10', name: 'Pin 10 (2PR)', type: 'IN', relativePos: [0.24, -0.22, -0.62], description: 'Preset (Active Low)', gateNumber: 2, gateRole: 'PR' },
      { id: 'pin-11', name: 'Pin 11 (2CLK)', type: 'IN', relativePos: [0.0, -0.22, -0.62], description: 'Clock Input', gateNumber: 2, gateRole: 'CLK' },
      { id: 'pin-12', name: 'Pin 12 (2D)', type: 'IN', relativePos: [-0.24, -0.22, -0.62], description: 'Data Input', gateNumber: 2, gateRole: 'D' },
      { id: 'pin-13', name: 'Pin 13 (2CLR)', type: 'IN', relativePos: [-0.48, -0.22, -0.62], description: 'Clear (Active Low)', gateNumber: 2, gateRole: 'CLR' },
      { id: 'pin-14', name: 'Pin 14 (VCC)', type: 'VCC', relativePos: [-0.72, -0.22, -0.62], description: 'VCC +5V', gateRole: 'VCC' },
    ],
    applications: ['Registers', 'Data Storage'],
    dimensions: { x: 1.8, y: 0.3, z: 0.8 },
  },
  {
    id: 'ic-sr-ff',
    name: 'Dual SR Flip-Flop',
    category: 'Logic & IC',
    tagline: 'Synchronous SR flip-flop',
    description: 'A dual SR flip-flop that can set or reset state based on S and R inputs at the clock edge.',
    workingPrinciple: 'Latches S or R inputs on the clock edge.',
    operatingVoltage: '4.75V to 5.25V',
    operatingCurrent: '15mA to 20mA',
    datasheetSummary: {
      manufacturer: 'Generic',
      interface: '14-pin DIP',
    },
    pins: [
      { id: 'pin-1', name: 'Pin 1 (1S)', type: 'IN', relativePos: [-0.72, -0.22, 0.62], description: 'Set Input', gateNumber: 1, gateRole: 'S' },
      { id: 'pin-2', name: 'Pin 2 (1R)', type: 'IN', relativePos: [-0.48, -0.22, 0.62], description: 'Reset Input', gateNumber: 1, gateRole: 'R' },
      { id: 'pin-3', name: 'Pin 3 (1CLK)', type: 'IN', relativePos: [-0.24, -0.22, 0.62], description: 'Clock Input', gateNumber: 1, gateRole: 'CLK' },
      { id: 'pin-4', name: 'Pin 4 (1Q)', type: 'OUT', relativePos: [0.0, -0.22, 0.62], description: 'Q Output', gateNumber: 1, gateRole: 'Q' },
      { id: 'pin-5', name: 'Pin 5 (1Q\\')', type: 'OUT', relativePos: [0.24, -0.22, 0.62], description: 'Inverted Q Output', gateNumber: 1, gateRole: 'Q_INV' },
      { id: 'pin-6', name: 'Pin 6 (NC)', type: 'IN', relativePos: [0.48, -0.22, 0.62], description: 'No Connection', gateNumber: 1, gateRole: 'NC' },
      { id: 'pin-7', name: 'Pin 7 (GND)', type: 'GND', relativePos: [0.72, -0.22, 0.62], description: 'Ground', gateRole: 'GND' },
      { id: 'pin-8', name: 'Pin 8 (NC)', type: 'IN', relativePos: [0.72, -0.22, -0.62], description: 'No Connection', gateNumber: 2, gateRole: 'NC' },
      { id: 'pin-9', name: 'Pin 9 (2Q\\')', type: 'OUT', relativePos: [0.48, -0.22, -0.62], description: 'Inverted Q Output', gateNumber: 2, gateRole: 'Q_INV' },
      { id: 'pin-10', name: 'Pin 10 (2Q)', type: 'OUT', relativePos: [0.24, -0.22, -0.62], description: 'Q Output', gateNumber: 2, gateRole: 'Q' },
      { id: 'pin-11', name: 'Pin 11 (2CLK)', type: 'IN', relativePos: [0.0, -0.22, -0.62], description: 'Clock Input', gateNumber: 2, gateRole: 'CLK' },
      { id: 'pin-12', name: 'Pin 12 (2R)', type: 'IN', relativePos: [-0.24, -0.22, -0.62], description: 'Reset Input', gateNumber: 2, gateRole: 'R' },
      { id: 'pin-13', name: 'Pin 13 (2S)', type: 'IN', relativePos: [-0.48, -0.22, -0.62], description: 'Set Input', gateNumber: 2, gateRole: 'S' },
      { id: 'pin-14', name: 'Pin 14 (VCC)', type: 'VCC', relativePos: [-0.72, -0.22, -0.62], description: 'VCC +5V', gateRole: 'VCC' },
    ],
    applications: ['Memory', 'State Latching'],
    dimensions: { x: 1.8, y: 0.3, z: 0.8 },
  },
  {
    id: 'ic-t-ff',
    name: 'Dual T Flip-Flop',
    category: 'Logic & IC',
    tagline: 'Synchronous Toggle flip-flop',
    description: 'A dual T flip-flop that toggles state when T is high at the clock edge.',
    workingPrinciple: 'Toggles output state on clock edge when T input is high.',
    operatingVoltage: '4.75V to 5.25V',
    operatingCurrent: '15mA to 20mA',
    datasheetSummary: {
      manufacturer: 'Generic',
      interface: '14-pin DIP',
    },
    pins: [
      { id: 'pin-1', name: 'Pin 1 (1T)', type: 'IN', relativePos: [-0.72, -0.22, 0.62], description: 'Toggle Input', gateNumber: 1, gateRole: 'T' },
      { id: 'pin-2', name: 'Pin 2 (1CLK)', type: 'IN', relativePos: [-0.48, -0.22, 0.62], description: 'Clock Input', gateNumber: 1, gateRole: 'CLK' },
      { id: 'pin-3', name: 'Pin 3 (1CLR)', type: 'IN', relativePos: [-0.24, -0.22, 0.62], description: 'Clear (Active Low)', gateNumber: 1, gateRole: 'CLR' },
      { id: 'pin-4', name: 'Pin 4 (1Q)', type: 'OUT', relativePos: [0.0, -0.22, 0.62], description: 'Q Output', gateNumber: 1, gateRole: 'Q' },
      { id: 'pin-5', name: 'Pin 5 (1Q\\')', type: 'OUT', relativePos: [0.24, -0.22, 0.62], description: 'Inverted Q Output', gateNumber: 1, gateRole: 'Q_INV' },
      { id: 'pin-6', name: 'Pin 6 (NC)', type: 'IN', relativePos: [0.48, -0.22, 0.62], description: 'No Connection', gateNumber: 1, gateRole: 'NC' },
      { id: 'pin-7', name: 'Pin 7 (GND)', type: 'GND', relativePos: [0.72, -0.22, 0.62], description: 'Ground', gateRole: 'GND' },
      { id: 'pin-8', name: 'Pin 8 (NC)', type: 'IN', relativePos: [0.72, -0.22, -0.62], description: 'No Connection', gateNumber: 2, gateRole: 'NC' },
      { id: 'pin-9', name: 'Pin 9 (2Q\\')', type: 'OUT', relativePos: [0.48, -0.22, -0.62], description: 'Inverted Q Output', gateNumber: 2, gateRole: 'Q_INV' },
      { id: 'pin-10', name: 'Pin 10 (2Q)', type: 'OUT', relativePos: [0.24, -0.22, -0.62], description: 'Q Output', gateNumber: 2, gateRole: 'Q' },
      { id: 'pin-11', name: 'Pin 11 (2CLR)', type: 'IN', relativePos: [0.0, -0.22, -0.62], description: 'Clear (Active Low)', gateNumber: 2, gateRole: 'CLR' },
      { id: 'pin-12', name: 'Pin 12 (2CLK)', type: 'IN', relativePos: [-0.24, -0.22, -0.62], description: 'Clock Input', gateNumber: 2, gateRole: 'CLK' },
      { id: 'pin-13', name: 'Pin 13 (2T)', type: 'IN', relativePos: [-0.48, -0.22, -0.62], description: 'Toggle Input', gateNumber: 2, gateRole: 'T' },
      { id: 'pin-14', name: 'Pin 14 (VCC)', type: 'VCC', relativePos: [-0.72, -0.22, -0.62], description: 'VCC +5V', gateRole: 'VCC' },
    ],
    applications: ['Counters', 'Frequency Dividers'],
    dimensions: { x: 1.8, y: 0.3, z: 0.8 },
  },
];
`;

const replaceIndex = code.lastIndexOf('];');
if (replaceIndex > -1) {
  code = code.substring(0, replaceIndex) + newICs + code.substring(replaceIndex + 2);
}

fs.writeFileSync('src/data/componentsLibrary.ts', code);
