/**
 * BreadboardConfig.js
 *
 * Single source of truth for every dimensional constant of the logical
 * breadboard. All linear values are in millimetres (units = 'mm').
 *
 * Overall board : 165.5 x 55 mm
 * Hole          : 1.0 mm diameter @ 2.54 mm pitch
 * Layout        : rows A-J (two banks of 5, separated by a 7.62 mm
 *                 center gap), columns 1-63.
 * Power rails   : NOT generated by design.
 */
export const BreadboardConfig = Object.freeze({
  units: 'mm',

  board: Object.freeze({
    length: 165.5,   // X axis
    width: 55.0,     // Y axis
  }),

  hole: Object.freeze({
    diameter: 1.0,
    radius: 0.5,
    pitch: 2.54,
    sphereRadius: 0.4,       // visualization sphere radius
    sphereColor: 0x808080,   // gray
  }),

  layout: Object.freeze({
    rows: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    rowsPerBank: 5,
    columns: 63,             // columns 1..63
    rowPitch: 2.54,
    columnPitch: 2.54,
    centerGap: 7.62,         // gap between row E and row F
  }),

  // Power rail rows (top -> bottom): PT = top positive, TN = top negative,
  // BP = bottom positive, BN = bottom negative.
  powerRail: Object.freeze({
    rails: ['PT', 'TN', 'BP', 'BN'],
    holesPerRail: 63,
    gapFromTerminalStrip: 7.62,  // 3 x 2.54 mm, same as the center gap
  }),

  epsilon: 1e-6,
});
